version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: school-management-nginx
    ports:
      - "80:80"     # expose nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build: .
    container_name: school-management-app
    ports:
      - "4000:4000"  # Node app port (optional to expose, as nginx will proxy)
    depends_on:
      - mongo
      - redis
      - kafka
    environment:
      - MONGODB_URI=mongodb://mongo:27017/school
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=your_jwt_secret_here
    volumes:
      - .:/usr/src/app
    command: npm run dev

  mongo:
    image: mongo:6
    container_name: school-db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
